name: Assets

on: [push]
#   schedule:
#     - cron:  '*/20 * * * *'

jobs:
  assets:
    name: Update local assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Get yarn cache
      #   id: yarn-cache
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      #- name: Build actions
      #  run: |
      #    yarn bootstrap
      #    yarn build

      - name: Fetch latest assets
        id: fetch
        working-directory: ./packages/adblocker/assets
        run: |
          ./update_lists.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: Rémi Berson <remusao@users.noreply.github.com>
          author: Rémi Berson <remusao@users.noreply.github.com>
          commit-message: "chore: update local assets"
          title: "chore: update local assets"
          labels: "PR: Internal :house:"
          reviewers: remusao
          branch: update-local-assets

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
